# Generated by Django 3.0.7 on 2020-08-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
    ]
