# Generated by Django 3.0.7 on 2020-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_produto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
